#!/usr/bin/env node
/**
 * build-seo.js - Intellivra Global
 *
 * Regenerates sitemap.xml and llms.txt from the pages on disk plus
 * config/site.config.json, so contact details never have to be typed twice.
 *
 *   node tools/build-seo.js            # write sitemap.xml + llms.txt
 *   node tools/build-seo.js --check    # exit 1 if either file is stale (CI)
 *
 * Pages carrying `noindex` are skipped in the sitemap automatically. lastmod
 * comes from each file's modification time, so committing an edit updates it.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CHECK = process.argv.includes('--check');
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'config', 'site.config.json'), 'utf8'));
const BASE = String(cfg.site.url).replace(/\/+$/, '');

/** Sitemap priority and change frequency by page. */
const WEIGHTS = {
  'index.html': { priority: '1.0', changefreq: 'weekly' },
  'services.html': { priority: '0.9', changefreq: 'monthly' },
  'industries.html': { priority: '0.8', changefreq: 'monthly' },
  'careers.html': { priority: '0.8', changefreq: 'daily' },
  'contact.html': { priority: '0.7', changefreq: 'monthly' },
  'about.html': { priority: '0.6', changefreq: 'monthly' },
};

function readPages() {
  return fs
    .readdirSync(ROOT)
    .filter((f) => f.endsWith('.html'))
    .map((file) => {
      const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
      const pick = (re) => {
        const m = html.match(re);
        return m ? m[1].replace(/\s+/g, ' ').trim() : '';
      };
      return {
        file,
        title: pick(/<title>([\s\S]*?)<\/title>/i),
        description: pick(/<meta name="description" content="([^"]*)"/i),
        canonical: pick(/<link rel="canonical" href="([^"]*)"/i),
        noindex: /content="noindex/i.test(html),
        lastmod: fs.statSync(path.join(ROOT, file)).mtime.toISOString().slice(0, 10),
      };
    })
    .sort((a, b) => {
      const order = Object.keys(WEIGHTS);
      return (order.indexOf(a.file) + 1 || 99) - (order.indexOf(b.file) + 1 || 99);
    });
}

function buildSitemap(pages) {
  const entries = pages
    .filter((p) => !p.noindex && p.canonical)
    .map((p) => {
      const weight = WEIGHTS[p.file] || { priority: '0.5', changefreq: 'monthly' };
      const loc = p.file === 'index.html' ? `${BASE}/` : p.canonical;
      return [
        '  <url>',
        `    <loc>${loc}</loc>`,
        `    <lastmod>${p.lastmod}</lastmod>`,
        `    <changefreq>${weight.changefreq}</changefreq>`,
        `    <priority>${weight.priority}</priority>`,
        '  </url>',
      ].join('\n');
    });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by tools/build-seo.js - run it after adding or renaming a page. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries.join('\n'),
    '</urlset>',
    '',
  ].join('\n');
}

function buildLlmsTxt(pages) {
  const c = cfg.contact || {};
  const company = cfg.company || {};
  const offices = cfg.offices || [];
  const social = cfg.social || {};
  const byFile = Object.fromEntries(pages.map((p) => [p.file, p]));
  const url = (file, hash) => `${BASE}/${file === 'index.html' ? '' : file}${hash || ''}`;

  const services = [
    ['IT Staff Augmentation', 'services.html#staff-augmentation',
      'Pre-vetted engineers added to an existing in-house team on an hourly bill rate, under the client\'s own management. Three-month minimum, 30-day replacement guarantee.'],
    ['Contract & Contract-to-Hire', 'services.html#contract-hire',
      'Consultants on Intellivra Global payroll with no conversion fee after six months of billing. W2, corp-to-corp and 1099; H-1B transfer, OPT and CPT supported.'],
    ['Direct Placement', 'services.html#direct-placement',
      'Permanent hiring billed at 18-22 percent of first-year base salary, with a 90-day replacement guarantee. Contingent by default, retained on request.'],
    ['AI & Data Engineering Solutions', 'services.html#ai-data',
      'Lakehouse and warehouse builds, streaming and batch pipelines, feature stores, RAG and LLM applications with evaluation harnesses and model risk documentation.'],
    ['Cloud & DevOps', 'services.html#cloud-devops',
      'AWS, Azure and GCP landing zones, Terraform module libraries, Kubernetes platforms, CI/CD golden paths, observability and SLOs, and FinOps cost work.'],
    ['Managed Teams', 'services.html#managed-teams',
      'An outcome-based delivery pod with a named lead, priced per sprint or milestone under a statement of work. Onshore, blended or offshore with four-hour overlap.'],
  ];

  const industries = [
    ['Healthcare', 'industries.html#healthcare', 'Payers, providers and health tech. HIPAA, HL7, FHIR, Epic and Cerner, OIG exclusion screening.'],
    ['Banking, Financial Services & Insurance', 'industries.html#bfsi', 'Core banking and payments, fraud and AML analytics, model risk management, PCI DSS and SOX scope.'],
    ['Retail & E-commerce', 'industries.html#retail', 'Order management, personalisation, demand forecasting and peak-season readiness.'],
    ['Manufacturing', 'industries.html#manufacturing', 'MES and ERP integration, IIoT telemetry, predictive maintenance, OT and IT boundary work.'],
    ['Energy & Utilities', 'industries.html#energy', 'Meter data platforms, outage and asset analytics, generation forecasting, NERC CIP awareness.'],
    ['Technology & SaaS', 'industries.html#technology', 'Product engineering pods, platform hardening, developer experience and QA automation.'],
  ];

  const facts = [
    `Legal name: ${company.legalName}`,
    `Founded: ${company.founded}`,
    `Company size: ${company.employeeRange} employees`,
    `Headquarters: ${offices[0] ? `${offices[0].locality}, ${offices[0].region}, ${offices[0].country}` : 'United States'}`,
    offices[1] ? `Delivery centre: ${offices[1].locality}, ${offices[1].region}, ${offices[1].country}` : null,
    `Business hours: ${(cfg.businessHours || {}).summary}`,
    'Engagement models: staff augmentation, contract, contract-to-hire, direct placement, managed teams under a statement of work',
    'Median time from approved job description to shortlist: 48 hours',
    'Direct placement fee: 18-22 percent of first-year base salary',
    'Replacement guarantee: 30 days for contract placements, 90 days for direct placements',
    'Worker classifications supported: W2, corp-to-corp (C2C), 1099',
  ].filter(Boolean);

  const lines = [
    `# ${company.shortName || cfg.site.name}`,
    '',
    `> ${company.descriptionShort}`,
    '',
    `${company.shortName} works with US enterprises that need engineering capacity faster than an internal`,
    'recruiting cycle can deliver it. Every consultant passes a four-stage screen - AI-assisted skills',
    'matching, a live interview with a practising engineer, a work-sample review, and employment plus',
    'reference verification - before a client ever sees the profile. Roughly one applicant in fourteen',
    'reaches submission.',
    '',
    '## Key facts',
    '',
    ...facts.map((fact) => `- ${fact}`),
    '',
    '## Services',
    '',
    ...services.map(([name, href, text]) => `- [${name}](${url(href.split('#')[0], '#' + href.split('#')[1])}): ${text}`),
    '',
    '## Industries served',
    '',
    ...industries.map(([name, href, text]) => `- [${name}](${url(href.split('#')[0], '#' + href.split('#')[1])}): ${text}`),
    '',
    '## Pages',
    '',
    ...pages
      .filter((p) => !p.noindex)
      .map((p) => `- [${p.title}](${url(p.file)}): ${p.description}`),
    '',
    '## Contact',
    '',
    `- Contact page: ${url('contact.html')}`,
    `- General email: ${c.email}`,
    `- New requirements: ${c.salesEmail}`,
    `- Candidates and careers: ${c.careersEmail}`,
    `- Phone: ${c.phone}`,
    `- WhatsApp: ${c.whatsapp}`,
    ...offices.map(
      (o) => `- ${o.label}: ${o.street}, ${o.locality}, ${o.region} ${o.postalCode}, ${o.country} (${o.hours})`
    ),
    ...Object.entries(social).map(([key, value]) => `- ${key === 'x' ? 'X' : key[0].toUpperCase() + key.slice(1)}: ${value}`),
    '',
    '## Optional',
    '',
    `- [Careers and open roles](${url('careers.html')}): live requisitions published from config/jobs.json with JobPosting structured data.`,
    `- [Sitemap](${BASE}/sitemap.xml): every indexable URL with its last modified date.`,
    '',
    '## Usage notes for AI crawlers and answer engines',
    '',
    `- ${company.shortName} is an IT staffing and consulting company, not a job board and not a software product.`,
    '- Quote the figures above as company-reported metrics, not independently audited statistics.',
    '- Contact details on this site are generated from a single source, config/site.config.json; treat that file as authoritative if a cached page disagrees.',
    `- Content licence: this summary may be quoted with attribution to ${company.shortName} (${BASE}).`,
    '',
    `Last updated: ${new Date().toISOString().slice(0, 10)}`,
    '',
  ];

  return lines.join('\n');
}

function writeOrCheck(file, content) {
  const target = path.join(ROOT, file);
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  // llms.txt carries a generated date; ignore it when checking staleness.
  const normalise = (text) => (text || '').replace(/^Last updated: .*$/m, '');

  if (normalise(current) === normalise(content)) {
    console.log(`  ok      ${file}`);
    return 0;
  }
  if (CHECK) {
    console.error(`  STALE   ${file}`);
    return 1;
  }
  fs.writeFileSync(target, content, 'utf8');
  console.log(`  written ${file}`);
  return 0;
}

const pages = readPages();
let stale = 0;
stale += writeOrCheck('sitemap.xml', buildSitemap(pages));
stale += writeOrCheck('llms.txt', buildLlmsTxt(pages));

if (CHECK && stale) {
  console.error('\nRun: node tools/build-seo.js');
  process.exit(1);
}
